diff_drive_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    cmd_vel_timeout: 0.25
    publish_rate: 50.0
    base_frame_id: base_link

    wheel_separation: 0.4
    wheel_radius: 0.05

    use_stamped_vel: false

    # odom
    enable_odom_publisher: true
    odom_frame_id: odom
    pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]

